# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150525143403) do

  create_table "active_admin_comments", force: true do |t|
    t.string   "namespace"
    t.text     "body"
    t.string   "resource_id",   null: false
    t.string   "resource_type", null: false
    t.integer  "author_id"
    t.string   "author_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "active_admin_comments", ["author_type", "author_id"], name: "index_active_admin_comments_on_author_type_and_author_id", using: :btree
  add_index "active_admin_comments", ["namespace"], name: "index_active_admin_comments_on_namespace", using: :btree
  add_index "active_admin_comments", ["resource_type", "resource_id"], name: "index_active_admin_comments_on_resource_type_and_resource_id", using: :btree

  create_table "admin_users", force: true do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "admin_users", ["email"], name: "index_admin_users_on_email", unique: true, using: :btree
  add_index "admin_users", ["reset_password_token"], name: "index_admin_users_on_reset_password_token", unique: true, using: :btree

  create_table "clientes", force: true do |t|
    t.string   "nombre"
    t.integer  "edad"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "fotosprofiles", force: true do |t|
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "mis_fotos_file_name"
    t.string   "mis_fotos_content_type"
    t.integer  "mis_fotos_file_size"
    t.datetime "mis_fotos_updated_at"
  end

  create_table "gadgets", force: true do |t|
    t.string   "nombre"
    t.string   "descripcion"
    t.boolean  "activado"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "calendario"
    t.boolean  "inicio"
    t.boolean  "calendar"
    t.boolean  "horarios"
    t.boolean  "push"
    t.boolean  "chat"
    t.boolean  "paypal"
    t.boolean  "promos"
    t.boolean  "reservasarticulos"
    t.boolean  "cita_previa"
    t.boolean  "llamada_telefono"
  end

  create_table "horarios_configs", force: true do |t|
    t.boolean  "l_0h"
    t.boolean  "l_1h"
    t.boolean  "l_2h"
    t.boolean  "l_3h"
    t.boolean  "l_4h"
    t.boolean  "l_5h"
    t.boolean  "l_6h"
    t.boolean  "l_7h"
    t.boolean  "l_730h"
    t.boolean  "l_8h"
    t.boolean  "l_830h"
    t.boolean  "l_9h"
    t.boolean  "l_930h"
    t.boolean  "l_10h"
    t.boolean  "l_1030h"
    t.boolean  "l_11h"
    t.boolean  "l_1130"
    t.boolean  "l_12h"
    t.boolean  "l_1230h"
    t.boolean  "l_13h"
    t.boolean  "l_1330h"
    t.boolean  "l_14h"
    t.boolean  "l_1430h"
    t.boolean  "l_15h"
    t.boolean  "l_1530h"
    t.boolean  "l_16h"
    t.boolean  "l_1630h"
    t.boolean  "l_17h"
    t.boolean  "l_1730h"
    t.boolean  "l_18h"
    t.boolean  "l_1830h"
    t.boolean  "l_19h"
    t.boolean  "l_1930h"
    t.boolean  "l_20h"
    t.boolean  "l_2030h"
    t.boolean  "l_21h"
    t.boolean  "l_2130h"
    t.boolean  "l_22h"
    t.boolean  "l_2230h"
    t.boolean  "l_23h"
    t.boolean  "l_2330h"
    t.boolean  "ma_0h"
    t.boolean  "ma_1h"
    t.boolean  "ma_2h"
    t.boolean  "ma_3h"
    t.boolean  "ma_4h"
    t.boolean  "ma_5h"
    t.boolean  "ma_6h"
    t.boolean  "ma_7h"
    t.boolean  "ma_730h"
    t.boolean  "ma_8h"
    t.boolean  "ma_830h"
    t.boolean  "ma_9h"
    t.boolean  "ma_930h"
    t.boolean  "ma_10h"
    t.boolean  "ma_1030h"
    t.boolean  "ma_11h"
    t.boolean  "ma_1130h"
    t.boolean  "ma_12h"
    t.boolean  "ma_1230h"
    t.boolean  "ma_13h"
    t.boolean  "ma_1330h"
    t.boolean  "ma_14h"
    t.boolean  "ma_1430h"
    t.boolean  "ma_15h"
    t.boolean  "ma_1530h"
    t.boolean  "ma_16h"
    t.boolean  "ma_1630h"
    t.boolean  "ma_17h"
    t.boolean  "ma_1730h"
    t.boolean  "ma_18h"
    t.boolean  "ma_1830h"
    t.boolean  "ma_19h"
    t.boolean  "ma_1930h"
    t.boolean  "ma_20h"
    t.boolean  "ma_2030h"
    t.boolean  "ma_21h"
    t.boolean  "ma_2130h"
    t.boolean  "ma_22h"
    t.boolean  "ma_2230h"
    t.boolean  "ma_23h"
    t.boolean  "ma_2330h"
    t.boolean  "mi_0h"
    t.boolean  "mi_1h"
    t.boolean  "mi_2h"
    t.boolean  "mi_3h"
    t.boolean  "mi_4h"
    t.boolean  "mi_5h"
    t.boolean  "mi_6h"
    t.boolean  "mi_7h"
    t.boolean  "mi_730h"
    t.boolean  "mi_8h"
    t.boolean  "mi_830h"
    t.boolean  "mi_9h"
    t.boolean  "mi_930h"
    t.boolean  "mi_10h"
    t.boolean  "mi_1030h"
    t.boolean  "mi_11h"
    t.boolean  "mi_1130h"
    t.boolean  "mi_12h"
    t.boolean  "mi_1230h"
    t.boolean  "mi_13h"
    t.boolean  "mi_1330h"
    t.boolean  "mi_14h"
    t.boolean  "mi_1430h"
    t.boolean  "mi_15h"
    t.boolean  "mi_1530h"
    t.boolean  "mi_16h"
    t.boolean  "mi_1630h"
    t.boolean  "mi_17h"
    t.boolean  "mi_1730h"
    t.boolean  "mi_18h"
    t.boolean  "mi_1830h"
    t.boolean  "mi_19h"
    t.boolean  "mi_1930h"
    t.boolean  "mi_20h"
    t.boolean  "mi_2030h"
    t.boolean  "mi_21h"
    t.boolean  "mi_2130h"
    t.boolean  "mi_22h"
    t.boolean  "mi_2230h"
    t.boolean  "mi_23h"
    t.boolean  "mi_2330h"
    t.boolean  "j_0h"
    t.boolean  "j_1h"
    t.boolean  "j_2h"
    t.boolean  "j_3h"
    t.boolean  "j_4h"
    t.boolean  "j_5h"
    t.boolean  "j_6h"
    t.boolean  "j_7h"
    t.boolean  "j_730h"
    t.boolean  "j_8h"
    t.boolean  "j_830h"
    t.boolean  "j_9h"
    t.boolean  "j_930h"
    t.boolean  "j_10h"
    t.boolean  "j_1030h"
    t.boolean  "j_11h"
    t.boolean  "j_1130h"
    t.boolean  "j_12h"
    t.boolean  "j_1230h"
    t.boolean  "j_13h"
    t.boolean  "j_1330h"
    t.boolean  "j_14h"
    t.boolean  "j_1430h"
    t.boolean  "j_15h"
    t.boolean  "j_1530h"
    t.boolean  "j_16h"
    t.boolean  "j_1630h"
    t.boolean  "j_17h"
    t.boolean  "j_1730h"
    t.boolean  "j_18h"
    t.boolean  "j_1830h"
    t.boolean  "j_19h"
    t.boolean  "j_1930h"
    t.boolean  "j_20h"
    t.boolean  "j_2030h"
    t.boolean  "j_21h"
    t.boolean  "j_2130h"
    t.boolean  "j_22h"
    t.boolean  "j_2230h"
    t.boolean  "j_23h"
    t.boolean  "j_2330h"
    t.boolean  "v_0h"
    t.boolean  "v_1h"
    t.boolean  "v_2h"
    t.boolean  "v_3h"
    t.boolean  "v_4h"
    t.boolean  "v_5h"
    t.boolean  "v_6h"
    t.boolean  "v_7h"
    t.boolean  "v_730h"
    t.boolean  "v_8h"
    t.boolean  "v_830h"
    t.boolean  "v_9h"
    t.boolean  "v_930h"
    t.boolean  "v_10h"
    t.boolean  "v_1030h"
    t.boolean  "v_11h"
    t.boolean  "v_1130h"
    t.boolean  "v_12h"
    t.boolean  "v_1230h"
    t.boolean  "v_13h"
    t.boolean  "v_1330h"
    t.boolean  "v_14h"
    t.boolean  "v_1430h"
    t.boolean  "v_15h"
    t.boolean  "v_1530h"
    t.boolean  "v_16h"
    t.boolean  "v_1630h"
    t.boolean  "v_17h"
    t.boolean  "v_1730h"
    t.boolean  "v_18h"
    t.boolean  "v_1830h"
    t.boolean  "v_19h"
    t.boolean  "v_1930h"
    t.boolean  "v_20h"
    t.boolean  "v_2030h"
    t.boolean  "v_21h"
    t.boolean  "v_2130h"
    t.boolean  "v_22h"
    t.boolean  "v_2230h"
    t.boolean  "v_23h"
    t.boolean  "v_2330h"
    t.boolean  "s_0h"
    t.boolean  "s_1h"
    t.boolean  "s_2h"
    t.boolean  "s_3h"
    t.boolean  "s_4h"
    t.boolean  "s_5h"
    t.boolean  "s_6h"
    t.boolean  "s_7h"
    t.boolean  "s_730h"
    t.boolean  "s_8h"
    t.boolean  "s_830h"
    t.boolean  "s_9h"
    t.boolean  "s_930h"
    t.boolean  "s_10h"
    t.boolean  "s_1030h"
    t.boolean  "s_11h"
    t.boolean  "s_1130h"
    t.boolean  "s_12h"
    t.boolean  "s_1230h"
    t.boolean  "s_13h"
    t.boolean  "s_14h"
    t.boolean  "s_1430h"
    t.boolean  "s_15h"
    t.boolean  "s_1530h"
    t.boolean  "s_16h"
    t.boolean  "s_1630h"
    t.boolean  "s_17h"
    t.boolean  "s_1730h"
    t.boolean  "s_18h"
    t.boolean  "s_1830h"
    t.boolean  "s_19h"
    t.boolean  "s_1930h"
    t.boolean  "s_20h"
    t.boolean  "s_2030h"
    t.boolean  "s_21h"
    t.boolean  "s_2130h"
    t.boolean  "s_22h"
    t.boolean  "s_2230h"
    t.boolean  "s_23h"
    t.boolean  "s_2330h"
    t.boolean  "d_0h"
    t.boolean  "d_1h"
    t.boolean  "d_2h"
    t.boolean  "d_3h"
    t.boolean  "d_4h"
    t.boolean  "d_5h"
    t.boolean  "d_6h"
    t.boolean  "d_7h"
    t.boolean  "d_730h"
    t.boolean  "d_8h"
    t.boolean  "d_830h"
    t.boolean  "d_9h"
    t.boolean  "d_930h"
    t.boolean  "d_10h"
    t.boolean  "d_1030h"
    t.boolean  "d_11h"
    t.boolean  "d_1130h"
    t.boolean  "d_12h"
    t.boolean  "d_1230h"
    t.boolean  "d_13h"
    t.boolean  "d_1330h"
    t.boolean  "d_14h"
    t.boolean  "d_1430h"
    t.boolean  "d_15h"
    t.boolean  "d_1530h"
    t.boolean  "d_16h"
    t.boolean  "d_1630h"
    t.boolean  "d_17h"
    t.boolean  "d_1730h"
    t.boolean  "d_18h"
    t.boolean  "d_1830h"
    t.boolean  "d_19h"
    t.boolean  "d_1930h"
    t.boolean  "d_20h"
    t.boolean  "d_2030h"
    t.boolean  "d_21h"
    t.boolean  "d_2130h"
    t.boolean  "d_22h"
    t.boolean  "d_2230h"
    t.boolean  "d_23h"
    t.boolean  "d_2330h"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "lun_930h"
    t.boolean  "martes_1130h"
    t.boolean  "miercoles_10h"
    t.boolean  "sabado_1330h"
  end

  create_table "myprofiles", force: true do |t|
    t.string   "descripcion"
    t.string   "informacion_util"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "fotoperfil_file_name"
    t.string   "fotoperfil_content_type"
    t.integer  "fotoperfil_file_size"
    t.datetime "fotoperfil_updated_at"
    t.text     "description"
    t.string   "nombredenegocio"
    t.string   "tiponegocio"
    t.string   "telf"
    t.string   "address"
    t.float    "latitude",                limit: 24
    t.float    "longitude",               limit: 24
    t.string   "cif"
  end

  create_table "people", force: true do |t|
    t.string   "nombre"
    t.integer  "edad"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "subirimagen_file_name"
    t.string   "subirimagen_content_type"
    t.integer  "subirimagen_file_size"
    t.datetime "subirimagen_updated_at"
  end

  create_table "personas", force: true do |t|
    t.string   "nombre"
    t.string   "apellidos"
    t.integer  "edad"
    t.string   "telefono"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pins", force: true do |t|
    t.string   "photo"
    t.string   "descripcion"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.integer  "user_id"
    t.string   "avatar_file_name"
    t.string   "avatar_content_type"
    t.integer  "avatar_file_size"
    t.datetime "avatar_updated_at"
    t.string   "categoria"
    t.integer  "precio"
    t.float    "price",               limit: 24
    t.integer  "stock"
    t.string   "referencia"
  end

  create_table "productos", force: true do |t|
    t.string   "nombre"
    t.float    "precio",     limit: 24
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "promos", force: true do |t|
    t.string   "nombre"
    t.string   "descripcion"
    t.string   "enlace"
    t.boolean  "seguir"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "fotospromo_file_name"
    t.string   "fotospromo_content_type"
    t.integer  "fotospromo_file_size"
    t.datetime "fotospromo_updated_at"
    t.boolean  "valido"
  end

  create_table "users", force: true do |t|
    t.string   "email",                             default: "", null: false
    t.string   "encrypted_password",                default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",                     default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "phone"
    t.string   "address"
    t.float    "latitude",               limit: 24
    t.float    "longitude",              limit: 24
    t.string   "nombrenegocio"
    t.string   "tipodenegocio"
    t.string   "cifempresa"
    t.boolean  "validado"
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree

  create_table "usuarios", force: true do |t|
    t.string   "nombre"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "curso"
    t.string   "Ciudad"
    t.string   "Pais"
    t.string   "Direccion"
    t.string   "Religion"
  end

end
